import { NextResponse } from 'next/server';

const openaiKey = process.env.OPENAI_API_KEY;
const anthropicKey = process.env.ANTHROPIC_API_KEY;
const grokKey = process.env.XAI_API_KEY;

async function callLLM(goal: string) {
  const prompt = `You are an expert autonomous marketing strategist for AImarkOS - an AI Marketing Operating System.

User goal: ${goal}

Provide a comprehensive, high-ROAS marketing strategy with the following structure:

**1. Target Audience**
- Primary persona(s)
- Pain points and desires

**2. Key Messaging**
- Core value proposition
- Headline ideas

**3. Recommended Channels**
- Best platforms and why (LinkedIn, Email, Google Ads, Instagram, etc.)

**4. Content Ideas**
- 3-5 specific content pieces or campaign concepts

**5. Expected Outcomes & Metrics**
- Projected ROAS or other KPIs
- Success benchmarks

**6. Actionable Next Steps**
- Clear, immediate actions the user/agency can take

Be specific, creative, professional, and results-oriented.`;

  // Priority: Claude → OpenAI
  if (anthropicKey) {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': anthropicKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: "claude-3-5-sonnet-20240620",
        max_tokens: 1500,
        messages: [{ role: "user", content: prompt }]
      })
    });
    const data = await response.json();
    return data.content?.[0]?.text || "Strategy generated by Claude.";
  }

  if (openaiKey) {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openaiKey}`
      },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [{ role: "user", content: prompt }]
      })
    });
    const data = await response.json();
    return data.choices?.[0]?.message?.content || "Strategy generated by GPT-4o.";
  }

  return "AI is ready. No LLM keys configured.";
}

export async function POST(request: Request) {
  try {
    const { goal } = await request.json();

    const result = await callLLM(goal || "Create a high-ROAS marketing campaign");

    return NextResponse.json({
      status: "✅ AI Crew executed",
      goal: goal,
      result: result,
      timestamp: new Date().toISOString()
    });

  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ 
      status: "❌ Error",
      error: error.message 
    }, { status: 500 });
  }
}
